#ifndef  _HASH_TABLES_DEFINE_CONSTANT_H_
#define  _HASH_TABLES_DEFINE_CONSTANT_H_

//#define		COUNT_USERS_20
#define		COUNT_USERS_1000
//#define		COUNT_USERS_100000
#define MAX_TIME_CONNECT	60
#define MAX_TIME_REGISTRY	20

#ifdef COUNT_USERS_20
	#define	CFG_SIP_REG_TABLE_SIZE				20
	#define	CFG_SIP_SESSIONS_TABLE_SIZE			200
	#define	CFG_SIP_REG_HASHTABLE_SIZE			100
	#define	CFG_SIP_SESSIONS_HASHTABLE_SIZE		100

	#define	MAX_NEW_BINARY_TREE					100
	#define	MAX_NEW_FREE_BUFFER					100
#else

#ifdef COUNT_USERS_1000
	#define	CFG_SIP_REG_TABLE_SIZE				1000
	#define	CFG_SIP_SESSIONS_TABLE_SIZE			4000
	#define	CFG_SIP_REG_HASHTABLE_SIZE			1000
	#define	CFG_SIP_SESSIONS_HASHTABLE_SIZE		1000

	#define	MAX_NEW_BINARY_TREE					1000
	#define	MAX_NEW_FREE_BUFFER					1000
#else

#ifdef COUNT_USERS_100000
	#define	CFG_SIP_REG_TABLE_SIZE				100000
	#define	CFG_SIP_SESSIONS_TABLE_SIZE			400000
	#define	CFG_SIP_REG_HASHTABLE_SIZE			1000
	#define	CFG_SIP_SESSIONS_HASHTABLE_SIZE		1000

	#define	MAX_NEW_BINARY_TREE					10000
	#define	MAX_NEW_FREE_BUFFER					10000
#else
	#define	CFG_SIP_REG_TABLE_SIZE				100
	#define	CFG_SIP_SESSIONS_TABLE_SIZE			200
	#define	CFG_SIP_REG_HASHTABLE_SIZE			100
	#define	CFG_SIP_SESSIONS_HASHTABLE_SIZE		100

	#define	MAX_NEW_BINARY_TREE					100
	#define	MAX_NEW_FREE_BUFFER					300
#endif //COUNT_USERS_100000

#endif //COUNT_USERS_1000

#endif //COUNT_USERS_20




#endif /* _HASH_TABLES_DEFINE_CONSTANT_H_ */ 
